apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-dep2
  labels:
    app: busy-dep2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy-dep2
  template:
    metadata:
      labels:
        app: busy-dep2
    spec:
      containers:
      - image: busybox
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox
      - image: ubuntu:18.04
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: ubuntu
      restartPolicy: Always
