apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-connector.fullname" . }}
  labels:
    {{- include "cluster-connector.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  resourceNames: ["kube-system"]
  verbs: ["get"]
